name: multi-app CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code with full history
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Clean Install Dependencies
      - name: Install Dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --legacy-peer-deps

      # Set Nx SHAs for affected commands
      - name: Set SHAs for Nx Affected
        uses: nrwl/nx-set-shas@v4

      # Build All Affected Apps
      - name: Build All Affected Apps
        run: npx nx affected -t build --configuration=production

      # Deploy Shell
      - name: Deploy Shell
        uses: w9jds/firebase-action@v2.0.0
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_TOKEN }}
        with:
          args: -P microdevfest-shell deploy --only hosting --config apps/shell/firebase.json

      # Deploy Home
      - name: Deploy Home
        uses: w9jds/firebase-action@v2.0.0
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_TOKEN }}
        with:
          args: -P microdevfest-home deploy --only hosting --config apps/home/firebase.json

      # Deploy Shop
      - name: Deploy Shop
        uses: w9jds/firebase-action@v2.0.0
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_TOKEN }}
        with:
          args: -P microdevfest-shop deploy --only hosting --config apps/shop/firebase.json
